image: python:3.6-alpine

stages:
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

Upload to PyPI:
  stage: deploy
  script:
    - twine upload dist/*
  only:
    - master
#end deploy